receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlphttp/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true
  prometheusremotewrite/mimir:
    endpoint: "http://mimir:9009/api/v1/push"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite/mimir]
